version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "8010:8010"
    depends_on:
      - backend
      - mysql-development
    networks:
      - my-network
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mysql-development
    networks:
      - my-network
  mysql-development:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: mydb
    ports:
      - "3308:3306"
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
